# Generated by Django 5.2.2 on 2025-06-07 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Coin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("createTime", models.DateTimeField(auto_now_add=True)),
                ("usedTime", models.DateTimeField(blank=True, null=True)),
                (
                    "itemID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.shopitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_coins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsored_coins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
