# Generated by Django 5.2.2 on 2025-06-07 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_product_amount_alter_purchasehistory_amount_coin"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasehistory",
            name="uid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
