# Generated by Django 5.2.2 on 2025-06-07 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopowner_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('shopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopowner')),
            ],
        ),
    ]
