# Generated by Django 5.2.2 on 2025-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_user_user_type_adminuser_disadvantageuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal User"),
                    ("disadvantage", "Disadvantaged User"),
                    ("admin", "Admin"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
