# Generated by Django 5.2.2 on 2025-06-07 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasehistory",
            name="uid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsored_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
