# Generated by Django 5.2.2 on 2025-06-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_purchasehistory_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasehistory",
            name="itemID",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="uid",
            field=models.IntegerField(),
        ),
    ]
