# Generated by Django 5.2.2 on 2025-06-07 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_purchasehistory_uid_purchasehistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_coins', to=settings.AUTH_USER_MODEL),
        ),
    ]
