# Generated by Django 5.2.2 on 2025-06-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_purchasehistory_itemid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="itemID",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coin",
            name="owner",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coin",
            name="sponsor",
            field=models.IntegerField(),
        ),
    ]
