# Generated by Django 5.2.2 on 2025-06-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_coin_itemid_alter_coin_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
