# Generated by Django 5.2.2 on 2025-06-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_coin_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="itemID",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coin",
            name="owner",
            field=models.IntegerField(default=0),
        ),
    ]
